CREATE DATABASE Energy_Output_Expenses;

CREATE TABLE EDUCATION_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE EMPLOYHH_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE HHSEX_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE HOUSEHOLDER_RACE_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE MONEYPY_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE SDESCENT_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE DWCYCLE_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE ELECVEH_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE LGTINLED_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE SMARTMETER_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE SOLAR_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE TVTYPE1_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE TYPETHERM_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE ACEQUIPM_PUB_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE ADQINSUL_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE EQUIPM_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE ROOFTYPE_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE TYPEHUQ_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE WALLTYPE_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE YEARMADERANGE_Index (
    Value INT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    PRIMARY KEY (Value)
);

CREATE TABLE demographics (
    DOEID INT NOT NULL PRIMARY KEY,
    HHSEX INT NOT NULL,
    HHAGE INT NOT NULL,
    EMPLOYHH INT NOT NULL,
    EDUCATION INT NOT NULL,
    SDESCENT INT NOT NULL,
    HOUSEHOLDER_RACE INT NOT NULL,
    NHSLDMEM INT NOT NULL,
    NUMCHILD INT NOT NULL,
    MONEYPY INT NOT NULL,
    TOTALBTU DECIMAL NOT NULL,
    TOTALDOL DECIMAL NOT NULL,
    FOREIGN KEY (HHSEX) REFERENCES HHSEX_Index(Value),
    FOREIGN KEY (EMPLOYHH) REFERENCES EMPLOYHH_Index(Value),
    FOREIGN KEY (EDUCATION) REFERENCES EDUCATION_Index(Value),
    FOREIGN KEY (SDESCENT) REFERENCES SDESCENT_Index(Value),
    FOREIGN KEY (HOUSEHOLDER_RACE) REFERENCES HOUSEHOLDER_RACE_Index(Value),
    FOREIGN KEY (MONEYPY) REFERENCES MONEYPY_Index(Value)
);

CREATE TABLE energy_efficient (
    DOEID INT NOT NULL PRIMARY KEY,
    DWCYCLE INT NOT NULL,
    TVTYPE1 INT NOT NULL,
    TYPETHERM INT NOT NULL,
    LGTINLED INT NOT NULL,
    SMARTMETER INT NOT NULL,
    SOLAR INT NOT NULL,
    ELECVEH INT NOT NULL,
    TOTALBTU DECIMAL NOT NULL,
    TOTALDOL DECIMAL NOT NULL,
    FOREIGN KEY (DWCYCLE) REFERENCES DWCYCLE_Index(Value),
    FOREIGN KEY (TVTYPE1) REFERENCES TVTYPE1_Index(Value),
    FOREIGN KEY (TYPETHERM) REFERENCES TYPETHERM_Index(Value),
    FOREIGN KEY (LGTINLED) REFERENCES LGTINLED_Index(Value),
    FOREIGN KEY (SMARTMETER) REFERENCES SMARTMETER_Index(Value),
    FOREIGN KEY (SOLAR) REFERENCES SOLAR_Index(Value),
    FOREIGN KEY (ELECVEH) REFERENCES ELECVEH_Index(Value)
);

CREATE TABLE housing_characteristics (
    DOEID INT NOT NULL PRIMARY KEY,
    TYPEHUQ INT NOT NULL,
    YEARMADERANGE INT NOT NULL,
    TOTROOMS INT NOT NULL,
    WALLTYPE INT NOT NULL,
    ROOFTYPE INT NOT NULL,
    ADQINSUL INT NOT NULL,
    NUMFRIG INT NOT NULL,
    EQUIPM INT NOT NULL,
    ACEQUIPM_PUB INT NOT NUll,
    TOTSQFT_EN INT NOT NULL,
    TOTALBTU DECIMAL NOT NULL,
    TOTALDOL DECIMAL NOT NULL,
    FOREIGN KEY (TYPEHUQ) REFERENCES TYPEHUQ_Index(Value),
    FOREIGN KEY (YEARMADERANGE) REFERENCES YEARMADERANGE_Index(Value),
    FOREIGN KEY (WALLTYPE) REFERENCES WALLTYPE_Index(Value),
    FOREIGN KEY (ROOFTYPE) REFERENCES ROOFTYPE_Index(Value),
    FOREIGN KEY (ADQINSUL) REFERENCES ADQINSUL_Index(Value),
    FOREIGN KEY (EQUIPM) REFERENCES EQUIPM_Index(Value),
    FOREIGN KEY (ACEQUIPM_PUB) REFERENCES ACEQUIPM_PUB_Index(Value)
);

CREATE TABLE regional (
    DOEID INT NOT NULL PRIMARY KEY,
    REGIONC	VARCHAR(2000) NOT NULL,
    DIVISION VARCHAR(2000) NOT NULL,
    state_postal VARCHAR(2) NOT NULL,
    BA_climate VARCHAR(2000) NOT NULL,
    TOTALBTU DECIMAL NOT NULL,
    TOTALDOL DECIMAL NOT NULL
);